version: "3.4"
volumes:
  pusher_nsqd:
  pusher_mysql:

services:
  cointracker:
    restart: always
    build:
      context: .
    env_file:
      - .env
    volumes:
      - ${PWD}/cointracker:/opt/cointracker/